In [329]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.metrics import r2_score,mean_squared_error


In [2]:
temperature = pd.read_csv('temperature.csv')
temperature

YEAR  ANNUAL  JAN-FEB  MAR-MAY  JUN-SEP  OCT-DEC
0   1961   24.00    18.98    26.11    27.06    21.17
1   1962   24.04    18.91    25.91    27.14    21.47
2   1963   24.15    19.07    25.57    27.21    22.04
3   1964   24.10    18.83    26.38    26.90    21.58
4   1965   24.07    19.22    25.24    27.08    22.10
..   ...     ...      ...      ...      ...      ...
59  2020   25.78      NaN      NaN      NaN      NaN
60  2021   25.90      NaN      NaN      NaN      NaN
61  2022   25.90      NaN      NaN      NaN      NaN
62  2023   26.20      NaN      NaN      NaN      NaN
63  2024   26.50      NaN      NaN      NaN      NaN

[64 rows x 6 columns]

In [3]:
temperature.drop(['JAN-FEB','MAR-MAY','JUN-SEP','OCT-DEC'],axis = 1,inplace = True)

In [4]:
temperature

YEAR  ANNUAL
0   1961   24.00
1   1962   24.04
2   1963   24.15
3   1964   24.10
4   1965   24.07
..   ...     ...
59  2020   25.78
60  2021   25.90
61  2022   25.90
62  2023   26.20
63  2024   26.50

[64 rows x 2 columns]

In [325]:
X = temperature[['YEAR']]
y = temperature['ANNUAL']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=42,shuffle = True)

In [326]:
TemperatureModel = LinearRegression()
TemperatureModel.fit(X_train, y_train)

LinearRegression()

In [327]:
y_pred = TemperatureModel.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse) 
print(f" mae : {mean_absolute_error(y_test,y_pred)}\n rmse : {rmse}\nscore : {r2_score(y_test,y_pred)}")

 mae : 0.3009978448766986
 rmse : 0.34871084312954537
score : 0.5657157330474861


In [328]:
res = TemperatureModel.predict([[2010],[2030],[2050]])
res

C:\Users\mail2\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25.09262844, 25.69242274, 26.29221703])

In [331]:
rainfall = pd.read_csv('rainfall.csv')

In [333]:
rainfall.head()

YEAR   JAN   FEB   MAR   APR   MAY    JUN    JUL    AUG    SEP    OCT  \
0  1961  26.1  34.8  26.0  28.5  77.6  192.9  336.6  287.6  234.9  122.2   
1  1962  12.6  21.6  16.0  43.6  70.8  137.1  281.6  276.9  211.0   78.4   
2  1963   6.8   9.8  41.7  50.6  60.9  168.0  258.6  316.7  164.9   99.1   
3  1964  18.6  14.1  19.0  40.0  52.1  177.2  345.7  273.7  200.4   67.4   
4  1965  11.8  28.1  26.7  45.1  52.7  116.1  270.1  192.8  129.5   34.0   

    NOV   DEC     ANN  Jan-Feb  Mar-May  Jun-Sep  Oct-Dec  
0  21.7  10.4  1399.2     60.9    132.1   1052.0    154.2  
1  18.3  29.9  1198.0     34.3    130.4    906.6    126.7  
2  28.4  15.5  1220.9     16.6    153.1    908.2    142.9  
3  22.8  13.3  1244.4     32.7    111.1    997.0    103.5  
4  18.2  22.2   947.4     39.9    124.6    708.5     74.4

In [339]:
rainfall.drop(['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC','Jan-Feb','Mar-May','Jun-Sep','Oct-Dec'],axis = 1,inplace = True)

In [340]:
rainfall.head()

YEAR     ANN
0  1961  1399.2
1  1962  1198.0
2  1963  1220.9
3  1964  1244.4
4  1965   947.4

In [627]:
X = rainfall[['YEAR']]
y = rainfall['ANN']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.46, random_state=42,shuffle = False)

In [628]:
RainfallModel = LinearRegression()
RainfallModel.fit(X_train, y_train)

LinearRegression()

In [631]:
y_pred = RainfallModel.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse) 
print(f" mae : {mean_absolute_error(y_test,y_pred)}\n rmse : {rmse}\nscore : {r2_score(y_test,y_pred)}")

 mae : 76.22212393162391
 rmse : 93.73044778522879
score : 0.011899270789333394


In [563]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
rmse

93.73044778522879

In [632]:
res = RainfallModel.predict([[2010],[2030],[2070]])
res

C:\Users\mail2\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1138.18126496, 1123.53032479, 1094.22844444])

In [19]:
CropYield = pd.read_csv('yield_df.csv')

In [633]:
CropYield.head(3)

Unnamed: 0     Area         Item  Year  hg/ha_yield  \
0           0  Albania        Maize  1990        36613   
1           1  Albania     Potatoes  1990        66667   
2           2  Albania  Rice, paddy  1990        23333   

   average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  
0                         1485.0              121.0     16.37  
1                         1485.0              121.0     16.37  
2                         1485.0              121.0     16.37

In [21]:
IND = CropYield[CropYield['Area']=='India']

In [634]:
IND.head(3)

Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  avg_temp
22  Maize  1990        15178                         1083.0     25.58
23  Maize  1990        15178                         1083.0     26.88
24  Maize  1990        15178                         1083.0     25.79

In [23]:
IND.reset_index(inplace = True)

In [25]:
IND = IND.drop(['index','Unnamed: 0','Area','pesticides_tonnes'],axis = 1 )

In [636]:
IND.head(3)

Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  avg_temp
22  Maize  1990        15178                         1083.0     25.58
23  Maize  1990        15178                         1083.0     26.88
24  Maize  1990        15178                         1083.0     25.79

In [27]:
IND['Item'].unique()

array(['Cassava', 'Maize', 'Potatoes', 'Rice, paddy', 'Sorghum',
       'Soybeans', 'Sweet potatoes', 'Wheat'], dtype=object)

In [28]:
Index = IND[(IND['Item'] == 'Cassava') | (IND['Item'] == 'Sorghum') | (IND['Item'] == 'Soybeans') | (IND['Item'] == 'Sweet potatoes')].index

In [29]:
IND.drop(Index,inplace = True)

In [637]:
IND.head(3)

Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  avg_temp
22  Maize  1990        15178                         1083.0     25.58
23  Maize  1990        15178                         1083.0     26.88
24  Maize  1990        15178                         1083.0     25.79

In [32]:
dummies = pd.get_dummies(IND.Item)

In [33]:
merged = pd.concat([IND,dummies],axis = 1)

In [34]:
merged.drop('Item',axis = 1,inplace = True)

In [638]:
merged.head()

Year  hg/ha_yield  average_rain_fall_mm_per_year  avg_temp  Maize  \
0  1990        15178                         1083.0     25.58   True   
1  1990        15178                         1083.0     26.88   True   
2  1990        15178                         1083.0     25.79   True   
3  1990        15178                         1083.0     24.10   True   
4  1990        15178                         1083.0     25.25   True   

   Potatoes  Rice, paddy  Wheat  
0     False        False  False  
1     False        False  False  
2     False        False  False  
3     False        False  False  
4     False        False  False

In [36]:
merged.duplicated().sum()

332

In [640]:
merged.drop_duplicates(inplace = True)

In [641]:
merged.reset_index(inplace = True)

In [643]:
merged.drop('index',axis = 1,inplace = True)

In [645]:
merged.head(3)


Year  hg/ha_yield  average_rain_fall_mm_per_year  avg_temp  Maize  \
0  1990        15178                         1083.0     25.58   True   
1  1990        15178                         1083.0     26.88   True   
2  1990        15178                         1083.0     25.79   True   

   Potatoes  Rice, paddy  Wheat  
0     False        False  False  
1     False        False  False  
2     False        False  False

In [43]:
merged.describe()

Year    hg/ha_yield  average_rain_fall_mm_per_year     avg_temp
count  1692.000000    1692.000000                         1692.0  1692.000000
mean   2001.529551   64653.014775                         1083.0    26.053924
std       7.085084   69033.550987                            0.0     0.866587
min    1990.000000   13763.000000                         1083.0    23.260000
25%    1995.000000   24140.000000                         1083.0    25.500000
50%    2001.000000   28124.000000                         1083.0    25.990000
75%    2008.000000   64186.750000                         1083.0    26.670000
max    2013.000000  227606.000000                         1083.0    28.850000

In [44]:
maize = merged.loc[merged['Maize']==True].drop(['Maize','Potatoes','Rice, paddy','Wheat'],axis = 1)

In [646]:
maize.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
0  1990                         1083.0     25.58        15178
1  1990                         1083.0     26.88        15178
2  1990                         1083.0     25.79        15178

In [647]:
col = ['Year','average_rain_fall_mm_per_year','avg_temp','hg/ha_yield']

In [648]:
maize = maize[col]

In [649]:
maize.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
0  1990                         1083.0     25.58        15178
1  1990                         1083.0     26.88        15178
2  1990                         1083.0     25.79        15178

In [653]:
maize.describe()

Year  average_rain_fall_mm_per_year    avg_temp   hg/ha_yield
count   423.000000                          423.0  423.000000    423.000000
mean   2001.529551                         1083.0   26.053924  19370.486998
std       7.091377                            0.0    0.867357   3693.215482
min    1990.000000                         1083.0   23.260000  13763.000000
25%    1995.000000                         1083.0   25.500000  16758.000000
50%    2001.000000                         1083.0   25.990000  18216.000000
75%    2008.000000                         1083.0   26.665000  23352.000000
max    2013.000000                         1083.0   28.850000  25726.000000

In [654]:
X = maize.iloc[:, :-1]
y = maize.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42, shuffle=True)

In [655]:
MaizePredictor = LinearRegression()
MaizePredictor.fit(X_train,y_train)

LinearRegression()

In [658]:
y_pred = MaizePredictor.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse) 
print(f" mae : {mean_absolute_error(y_test,y_pred)}\n rmse : {rmse}\nscore : {r2_score(y_test,y_pred)}")

 mae : 1156.113450253034
 rmse : 1356.4177080781565
score : 0.8850159924244856


In [659]:
res = MaizePredictor.predict([[2050,1000,24],[2033,1100,25.5],[2029,1140,26]])
res

C:\Users\mail2\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([42990.61768899, 34612.00829638, 32622.94098656])

In [58]:
potatoes = merged.loc[merged['Potatoes']==True].drop(['Maize','Potatoes','Rice, paddy','Wheat'],axis = 1)

In [660]:
potatoes.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
18  1990                         1083.0     25.58      15713.6
19  1990                         1083.0     26.88      15713.6
20  1990                         1083.0     25.79      15713.6

In [60]:
potatoes = potatoes[col]

In [661]:
potatoes.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
18  1990                         1083.0     25.58      15713.6
19  1990                         1083.0     26.88      15713.6
20  1990                         1083.0     25.79      15713.6

In [63]:
potatoes['hg/ha_yield'] = potatoes['hg/ha_yield']/10

In [663]:
potatoes.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
18  1990                         1083.0     25.58      15713.6
19  1990                         1083.0     26.88      15713.6
20  1990                         1083.0     25.79      15713.6

In [664]:
X = potatoes.iloc[:, :-1]
y = potatoes.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42, shuffle=True)

In [665]:
PotatoesPredictor = LinearRegression()
PotatoesPredictor.fit(X_train,y_train)

LinearRegression()

In [666]:
y_pred = PotatoesPredictor.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse) 
print(f" mae : {mean_absolute_error(y_test,y_pred)}\n rmse : {rmse}\nscore : {r2_score(y_test,y_pred)}")

 mae : 959.6770384603618
 rmse : 1260.9665809242413
score : 0.7452412623453032


In [667]:
res = PotatoesPredictor.predict([[2010,1000,24],[2019,1100,25.5],[2080,1240,28]])
res

C:\Users\mail2\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([20570.36271844, 22676.95748388, 37800.35606957])

In [72]:
paddy = merged.loc[merged['Rice, paddy']==True].drop(['Maize','Potatoes','Rice, paddy','Wheat'],axis = 1)

In [668]:
paddy.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
36  1990                         1083.0     25.58        26125
37  1990                         1083.0     26.88        26125
38  1990                         1083.0     25.79        26125

In [74]:
paddy = paddy[col]

In [669]:
paddy.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
36  1990                         1083.0     25.58        26125
37  1990                         1083.0     26.88        26125
38  1990                         1083.0     25.79        26125

In [670]:
X = paddy.iloc[:, :-1]
y = paddy.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42, shuffle=True)

In [671]:
PaddyPredictor = LinearRegression()
PaddyPredictor.fit(X_train,y_train)

LinearRegression()

In [672]:
y_pred = PaddyPredictor.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse) 
print(f" mae : {mean_absolute_error(y_test,y_pred)}\n rmse : {rmse}\nscore : {r2_score(y_test,y_pred)}")

 mae : 994.6761789608199
 rmse : 1291.3210399169807
score : 0.853910251857801


In [673]:
res = PaddyPredictor.predict([[2010,1000,24],[2025,1100,25.5],[2080,1240,28]])
res

C:\Users\mail2\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([34397.87953924, 40498.84571473, 63555.9838177 ])

In [82]:
wheat = merged.loc[merged['Wheat']==True].drop(['Maize','Potatoes','Rice, paddy','Wheat'],axis = 1)

In [674]:
wheat.head(3)

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
54  1990                         1083.0     25.58        21211
55  1990                         1083.0     26.88        21211
56  1990                         1083.0     25.79        21211

In [84]:
wheat = wheat[col]

In [85]:
wheat

Year  average_rain_fall_mm_per_year  avg_temp  hg/ha_yield
54    1990                         1083.0     25.58        21211
55    1990                         1083.0     26.88        21211
56    1990                         1083.0     25.79        21211
57    1990                         1083.0     24.10        21211
58    1990                         1083.0     25.25        21211
...    ...                            ...       ...          ...
1687  2013                         1083.0     25.85        31538
1688  2013                         1083.0     27.14        31538
1689  2013                         1083.0     25.98        31538
1690  2013                         1083.0     27.44        31538
1691  2013                         1083.0     26.99        31538

[423 rows x 4 columns]

In [675]:
X = wheat.iloc[:, :-1]
y = wheat.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42, shuffle=True)

In [676]:
WheatPredictor = LinearRegression()
WheatPredictor.fit(X_train,y_train)

LinearRegression()

In [677]:
y_pred = WheatPredictor.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse) 
print(f" mae : {mean_absolute_error(y_test,y_pred)}\n rmse : {rmse}\nscore : {r2_score(y_test,y_pred)}")

 mae : 832.1196320809287
 rmse : 1034.5341987857014
score : 0.8695491721479851


In [678]:
res = WheatPredictor.predict([[2010,1000,24],[2025,1100,25.5],[2080,1240,28]])
res

C:\Users\mail2\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([29381.44126031, 34327.66496107, 52454.64599038])

In [92]:
sea = pd.read_csv('sea-level.csv')

In [679]:
sea.head(3)

Year  Sea Level
0  1880   0.000000
1  1881   0.220472
2  1882  -0.440945

In [680]:
sea.isnull().sum()

Year         0
Sea Level    0
dtype: int64

In [681]:
X = sea[['Year']]
y = sea[['Sea Level']]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9, random_state=42, shuffle=True)

In [682]:
SeaLevelPredictor = LinearRegression()
SeaLevelPredictor.fit(X_train,y_train)

LinearRegression()

In [683]:
y_pred = SeaLevelPredictor.predict(X_test)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse) 
print(f" mae : {mean_absolute_error(y_test,y_pred)}\n rmse : {rmse}\nscore : {r2_score(y_test,y_pred)}")

 mae : 0.4897515488004123
 rmse : 0.602952372510386
score : 0.947944238304654


In [684]:
mse = mean_squared_error(y_test,y_pred)
rmse =  np.sqrt(mse)
rmse

0.602952372510386

In [685]:
res = SeaLevelPredictor.predict([[2015],[2025],[2035],[2056]])
res

C:\Users\mail2\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 8.1624786 ],
       [ 8.81432265],
       [ 9.46616669],
       [10.83503919]])

In [101]:
import pickle

In [102]:
pickle.dump(TemperatureModel,open('TemperatureModel.pkl','wb'))
pickle.dump(RainfallModel,open('RainfallModel.pkl','wb'))
pickle.dump(MaizePredictor,open('MaizePredictor.pkl','wb'))
pickle.dump(PotatoesPredictor,open('PotatoesPredictor.pkl','wb'))
pickle.dump(PaddyPredictor,open('PaddyPredictor.pkl','wb'))
pickle.dump(WheatPredictor,open('WheatPredictor.pkl','wb'))
pickle.dump(SeaLevelPredictor,open('SeaLevelPredictor.pkl','wb'))